{{- if and .Values.postgrest.enabled (not .Values.postgrest.existingSecret) }}
{{- $uri := .Values.postgrest.connectionString }}
{{- if not $uri }}
  {{- $u := .Values.backends.postgres }}
  {{- if and $u.host $u.db }}
    {{- $uri = printf "postgres://%s@%s:%v/%s" .Values.postgrest.db.anonRole $u.host $u.port $u.db }}
  {{- end }}
{{- end }}
{{- if not $uri }}
  {{- fail "postgrest.enabled=true but neither postgrest.connectionString nor (backends.postgres.host + backends.postgres.db) are set." }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "davi.fullname" . }}-postgrest
  labels:
    {{- include "davi.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgrest
type: Opaque
stringData:
  uri: {{ $uri | quote }}
  {{- if .Values.postgrest.db.jwt.secret }}
  jwt-secret: {{ .Values.postgrest.db.jwt.secret | quote }}
  {{- end }}
{{- end }}
