{{- if .Values.discovery.sidecar.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "davi.fullname" . }}-discover
  labels:
    {{- include "davi.labels" . | nindent 4 }}
{{- end }}
