{{- if .Values.postgrest.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "davi.fullname" . }}-postgrest
  labels:
    {{- include "davi.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgrest
spec:
  type: ClusterIP
  selector:
    {{- include "davi.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgrest
  ports:
    - name: http
      port: {{ .Values.postgrest.service.port }}
      targetPort: http
      protocol: TCP
{{- end }}
